const WHATSAPP = '5511947717447'; // BT Veículos Jundiaí

const VEHICLES = [
  {
    id: 1,
    destaque: true,
    marca: 'Toyota',
    modelo: 'Corolla',
    versao: 'XEi Flex 2.0 Completo',
    ano: 2015,
    anoModelo: 2015,
    km: 85500,
    uso: 'usado',
    cambio: 'automático',
    combustivel: 'Flex',
    cor: 'Cinza',
    preco: 72900,
    img: '/carros/corolla-xei-2015.jpg',
    heroImg: '/carros/corolla-hero.png',
    opcionais: ['Ar-condicionado', 'Direção elétrica', 'Vidros elétricos', 'Câmera de ré', 'Bancos em couro', 'Central multimídia'],
    desc: 'Corolla XEi 2.0 Flex automático completo. Carro revisado, pronto para uso. Sedan espaçoso e confortável.'
  },
  {
    id: 2,
    destaque: true,
    marca: 'Hyundai',
    modelo: 'HB20',
    versao: 'Sense 1.0 Flex 12V Mec. Completo',
    ano: 2023,
    anoModelo: 2023,
    km: 88500,
    uso: 'seminovo',
    cambio: 'manual',
    combustivel: 'Flex',
    cor: 'Preto',
    preco: 64900,
    img: '/carros/hb20-sense-2023.jpg',
    heroImg: '/carros/hb20-hero.png',
    opcionais: ['Ar-condicionado', 'Direção elétrica', 'Vidros elétricos', 'Central multimídia', 'Alarme'],
    desc: 'HB20 Sense 1.0 Flex completo. Design moderno, econômico e revisado. Ótimo para o dia a dia.'
  },
  {
    id: 3,
    destaque: true,
    marca: 'Nissan',
    modelo: 'Kicks',
    versao: '1.6 Sense 16V Flex Completo',
    ano: 2024,
    anoModelo: 2024,
    km: 93800,
    uso: 'seminovo',
    cambio: 'automático',
    combustivel: 'Flex',
    cor: 'Prata',
    preco: 109900,
    img: '/carros/kicks-sense-2024.jpg',
    heroImg: '/carros/kicks-hero.png',
    opcionais: ['Ar-condicionado digital', 'Direção elétrica', 'Vidros elétricos', 'Central multimídia', 'Câmera de ré', 'Piloto automático'],
    desc: 'Kicks Sense 1.6 Flex automático completo. SUV moderno com tecnologia e conforto. Revisado.'
  },
  {
    id: 4,
    destaque: true,
    marca: 'BMW',
    modelo: '118i',
    versao: '2.0 16V Completa',
    ano: 2010,
    anoModelo: 2010,
    km: 80500,
    uso: 'usado',
    cambio: 'automático',
    combustivel: 'Gasolina',
    cor: 'Prata',
    preco: 54900,
    img: '/carros/bmw-118i-2010.jpg',
    heroImg: '/carros/bmw-hero.png',
    opcionais: ['Ar-condicionado', 'Direção elétrica', 'Vidros elétricos', 'Teto solar', 'Bancos em couro', 'Rodas 18"'],
    desc: 'BMW 118i 2.0 16V automática completa. Esportiva, econômica e com baixa quilometragem. Oportunidade!'
  },
  {
    id: 5,
    destaque: false,
    marca: 'Chevrolet',
    modelo: 'Onix',
    versao: 'Hatch LT 1.0 12V',
    ano: 2022,
    anoModelo: 2022,
    km: 138736,
    uso: 'seminovo',
    cambio: 'manual',
    combustivel: 'Flex',
    cor: 'Branco',
    preco: 59900,
    img: '/carros/onix-lt-2022.jpg',
    heroImg: '/carros/onix-hero.png',
    opcionais: ['Ar-condicionado', 'Direção elétrica', 'Vidros elétricos', 'MyLink', 'Câmera de ré'],
    desc: 'Onix Hatch LT 1.0 completo. Carro econômico, moderno e revisado na rede Chevrolet.'
  },
  {
    id: 6,
    destaque: false,
    marca: 'Fiat',
    modelo: 'Cronos',
    versao: '1.0 16V Flex Completo',
    ano: 2023,
    anoModelo: 2023,
    km: 85900,
    uso: 'seminovo',
    cambio: 'manual',
    combustivel: 'Flex',
    cor: 'Branco',
    preco: 64900,
    img: '/carros/cronos-2023.jpg',
    heroImg: '/carros/cronos-hero.png',
    opcionais: ['Ar-condicionado', 'Direção elétrica', 'Vidros elétricos', 'Central multimídia', 'Sensor de estacionamento'],
    desc: 'Cronos 1.0 Flex completo. Sedan compacto moderno, espaçoso e econômico. Revisado com garantia.'
  },
  {
    id: 7,
    destaque: false,
    marca: 'Volkswagen',
    modelo: 'Kombi',
    versao: 'Furgão 1.4 80CV',
    ano: 2009,
    anoModelo: 2009,
    km: 174000,
    uso: 'usado',
    cambio: 'manual',
    combustivel: 'Flex',
    cor: 'Branco',
    preco: 34900,
    img: '/carros/kombi-furgao-2009.jpg',
    heroImg: '/carros/kombi-hero.png',
    opcionais: ['Direção hidráulica'],
    desc: 'Kombi Furgão 1.4 Flex. Ideal para trabalho e entregas. Revisada e em bom estado de conservação.'
  },
  {
    id: 8,
    destaque: false,
    marca: 'Chevrolet',
    modelo: 'Classic',
    versao: 'LS 1.0 Completo',
    ano: 2015,
    anoModelo: 2015,
    km: 135000,
    uso: 'usado',
    cambio: 'manual',
    combustivel: 'Gasolina',
    cor: 'Branco',
    preco: 32900,
    img: '/carros/classic-ls-2015.jpg',
    heroImg: '/carros/classic-hero.png',
    opcionais: ['Ar-condicionado', 'Direção hidráulica', 'Vidros elétricos', 'Trava elétrica'],
    desc: 'Classic LS 1.0 completo. Carro econômico e confiável, ideal para primeiro carro ou trabalho.'
  }
];
