const WHATSAPP = '5511947717447';

const VEHICLES = [
  {
    "id": 1,
    "destaque": false,
    "marca": "Volkswagen",
    "modelo": "Voyage",
    "versao": "1.0 Flex 12V 4P G Completo",
    "ano": 2022,
    "anoModelo": 2023,
    "km": 177500,
    "uso": "seminovo",
    "cambio": "manual",
    "combustivel": "Flex",
    "cor": "Preto",
    "preco": 59900,
    "img": "/carros/volkswagen-voyage-2022-5.jpg",
    "heroImg": "",
    "opcionais": [
      "Ar-condicionado",
      "Direção elétrica",
      "Vidros elétricos"
    ],
    "desc": "Voyage 1.0 Flex completo. Econômico e espaçoso.",
    "fotos": [
      "/carros/volkswagen-voyage-2022-5.jpg",
      "/carros/volkswagen-voyage-2022-1.jpg",
      "/carros/volkswagen-voyage-2022-2.jpg",
      "/carros/volkswagen-voyage-2022-3.jpg",
      "/carros/volkswagen-voyage-2022-4.jpg",
      "/carros/volkswagen-voyage-2022-6.jpg",
      "/carros/volkswagen-voyage-2022-7.jpg",
      "/carros/volkswagen-voyage-2022-8.jpg",
      "/carros/volkswagen-voyage-2022-9.jpg",
      "/carros/volkswagen-voyage-2022-10.jpg"
    ]
  },
  {
    "id": 2,
    "destaque": false,
    "marca": "Volkswagen",
    "modelo": "Fox",
    "versao": "1.6 Run Completo",
    "ano": 2016,
    "anoModelo": 2017,
    "km": 164000,
    "uso": "usado",
    "cambio": "manual",
    "combustivel": "Flex",
    "cor": "Prata",
    "preco": 57400,
    "img": "/carros/volkswagen-fox-2016-2.jpg",
    "heroImg": "",
    "opcionais": [
      "Ar-condicionado",
      "Direção elétrica",
      "Vidros elétricos"
    ],
    "desc": "Fox 1.6 Run completo. Versátil e econômico.",
    "fotos": [
      "/carros/volkswagen-fox-2016-2.jpg",
      "/carros/volkswagen-fox-2016-1.jpg",
      "/carros/volkswagen-fox-2016-3.jpg",
      "/carros/volkswagen-fox-2016-4.jpg",
      "/carros/volkswagen-fox-2016-5.jpg",
      "/carros/volkswagen-fox-2016-6.jpg"
    ]
  },
  {
    "id": 3,
    "destaque": true,
    "marca": "Volkswagen",
    "modelo": "Kombi",
    "versao": "Furgão 1.4 80CV",
    "ano": 2009,
    "anoModelo": 2009,
    "km": 174000,
    "uso": "usado",
    "cambio": "manual",
    "combustivel": "Flex",
    "cor": "Branco",
    "preco": 39900,
    "img": "/carros/kombi-furgao-2009.jpg",
    "heroImg": "/carros/kombi-hero.png",
    "opcionais": [
      "Direção hidráulica"
    ],
    "desc": "Kombi Furgão 1.4 Flex. Ideal para trabalho e entregas. Revisada."
  },
  {
    "id": 4,
    "destaque": false,
    "marca": "Fiat",
    "modelo": "Linea",
    "versao": "HLX 1.8 16V Banco de Couro Completo MT",
    "ano": 2010,
    "anoModelo": 2011,
    "km": 142500,
    "uso": "usado",
    "cambio": "manual",
    "combustivel": "Flex",
    "cor": "Prata",
    "preco": 39900,
    "img": "/carros/linea.jpg",
    "heroImg": "",
    "opcionais": [
      "Ar-condicionado",
      "Bancos em couro",
      "Direção elétrica",
      "Vidros elétricos"
    ],
    "desc": "Linea HLX 1.8 completo com banco de couro."
  },
  {
    "id": 5,
    "destaque": false,
    "marca": "Fiat",
    "modelo": "Uno",
    "versao": "Sporting 1.4 Evo Fire Completo",
    "ano": 2012,
    "anoModelo": 2013,
    "km": 275126,
    "uso": "usado",
    "cambio": "manual",
    "combustivel": "Flex",
    "cor": "Laranja",
    "preco": 43900,
    "img": "/carros/fiat-uno-2012-1.jpg",
    "heroImg": "",
    "opcionais": [
      "Ar-condicionado",
      "Direção elétrica",
      "Vidros elétricos"
    ],
    "desc": "Uno Sporting 1.4 completo. Esportivo e econômico.",
    "fotos": [
      "/carros/fiat-uno-2012-1.jpg",
      "/carros/fiat-uno-2012-2.jpg",
      "/carros/fiat-uno-2012-3.jpg",
      "/carros/fiat-uno-2012-4.jpg",
      "/carros/fiat-uno-2012-5.jpg",
      "/carros/fiat-uno-2012-6.jpg",
      "/carros/fiat-uno-2012-7.jpg",
      "/carros/fiat-uno-2012-8.jpg",
      "/carros/fiat-uno-2012-9.jpg"
    ]
  },
  {
    "id": 6,
    "destaque": false,
    "marca": "Fiat",
    "modelo": "Argo",
    "versao": "1.3 Fire Flex Drive GSR Banco de Couro Completo Automático",
    "ano": 2018,
    "anoModelo": 2018,
    "km": 136000,
    "uso": "usado",
    "cambio": "automático",
    "combustivel": "Flex",
    "cor": "Prata",
    "preco": 63900,
    "img": "/carros/fiat-argo-2018-1.jpg",
    "heroImg": "",
    "opcionais": [
      "Ar-condicionado",
      "Bancos em couro",
      "Câmera de ré",
      "Central multimídia",
      "Direção elétrica"
    ],
    "desc": "Argo Drive 1.3 automático com banco de couro. Completo.",
    "fotos": [
      "/carros/fiat-argo-2018-1.jpg",
      "/carros/fiat-argo-2018-2.jpg",
      "/carros/fiat-argo-2018-3.jpg",
      "/carros/fiat-argo-2018-4.jpg",
      "/carros/fiat-argo-2018-5.jpg",
      "/carros/fiat-argo-2018-6.jpg",
      "/carros/fiat-argo-2018-7.jpg",
      "/carros/fiat-argo-2018-8.jpg",
      "/carros/fiat-argo-2018-9.jpg",
      "/carros/fiat-argo-2018-10.jpg",
      "/carros/fiat-argo-2018-11.jpg"
    ]
  },
  {
    "id": 7,
    "destaque": false,
    "marca": "Fiat",
    "modelo": "Cronos",
    "versao": "1.0 6V Flex Completo",
    "ano": 2023,
    "anoModelo": 2023,
    "km": 85900,
    "uso": "seminovo",
    "cambio": "manual",
    "combustivel": "Flex",
    "cor": "Branca",
    "preco": 63900,
    "img": "/carros/fiat-cronos-2023-1.jpg",
    "heroImg": "/carros/cronos-hero.png",
    "opcionais": [
      "Ar-condicionado",
      "Direção elétrica",
      "Vidros elétricos",
      "Central multimídia",
      "Sensor de estacionamento"
    ],
    "desc": "Cronos 1.0 Flex completo. Sedan compacto moderno.",
    "fotos": [
      "/carros/fiat-cronos-2023-1.jpg",
      "/carros/fiat-cronos-2023-2.jpg",
      "/carros/fiat-cronos-2023-3.jpg",
      "/carros/fiat-cronos-2023-4.jpg",
      "/carros/fiat-cronos-2023-5.jpg",
      "/carros/fiat-cronos-2023-6.jpg",
      "/carros/fiat-cronos-2023-7.jpg",
      "/carros/fiat-cronos-2023-8.jpg",
      "/carros/fiat-cronos-2023-9.jpg",
      "/carros/fiat-cronos-2023-10.jpg",
      "/carros/fiat-cronos-2023-11.jpg"
    ]
  },
  {
    "id": 8,
    "destaque": false,
    "marca": "Ford",
    "modelo": "Fiesta",
    "versao": "Class 1.6 8V Flex Completo",
    "ano": 2011,
    "anoModelo": 2012,
    "km": 174726,
    "uso": "usado",
    "cambio": "manual",
    "combustivel": "Flex",
    "cor": "Preto",
    "preco": 44900,
    "img": "/carros/ford-fiesta-2011-2.jpg",
    "heroImg": "",
    "opcionais": [
      "Ar-condicionado",
      "Direção elétrica",
      "Vidros elétricos"
    ],
    "desc": "Fiesta Class 1.6 completo. Compacto e econômico.",
    "fotos": [
      "/carros/ford-fiesta-2011-2.jpg",
      "/carros/ford-fiesta-2011-5.jpg",
      "/carros/ford-fiesta-2011-1.jpg",
      "/carros/ford-fiesta-2011-3.jpg",
      "/carros/ford-fiesta-2011-4.jpg",
      "/carros/ford-fiesta-2011-6.jpg"
    ]
  },
  {
    "id": 9,
    "destaque": true,
    "marca": "Nissan",
    "modelo": "Kicks",
    "versao": "1.6 Sense 16V Automático Completo",
    "ano": 2024,
    "anoModelo": 2024,
    "km": 93800,
    "uso": "seminovo",
    "cambio": "automático",
    "combustivel": "Flex",
    "cor": "Prata",
    "preco": 99800,
    "img": "/carros/kicks-sense-2024.jpg",
    "heroImg": "/carros/kicks-hero.png",
    "opcionais": [
      "Ar-condicionado digital",
      "Direção elétrica",
      "Câmera de ré",
      "Central multimídia",
      "Piloto automático"
    ],
    "desc": "Kicks Sense 1.6 Flex automático completo. SUV moderno."
  },
  {
    "id": 10,
    "destaque": false,
    "marca": "Chevrolet",
    "modelo": "Onix Hatch",
    "versao": "Hatch Lt 1.0 12V MT6",
    "ano": 2021,
    "anoModelo": 2022,
    "km": 138736,
    "uso": "seminovo",
    "cambio": "manual",
    "combustivel": "Flex",
    "cor": "Branco",
    "preco": 63850,
    "img": "/carros/chevrolet-onix-2021-6.jpg",
    "heroImg": "/carros/onix-hero.png",
    "opcionais": [
      "Ar-condicionado",
      "MyLink",
      "Câmera de ré",
      "Direção elétrica"
    ],
    "desc": "Onix Hatch LT 1.0. Moderno e econômico.",
    "fotos": [
      "/carros/chevrolet-onix-2021-6.jpg",
      "/carros/chevrolet-onix-2021-1.jpg",
      "/carros/chevrolet-onix-2021-2.jpg",
      "/carros/chevrolet-onix-2021-3.jpg",
      "/carros/chevrolet-onix-2021-4.jpg",
      "/carros/chevrolet-onix-2021-5.jpg",
      "/carros/chevrolet-onix-2021-7.jpg",
      "/carros/chevrolet-onix-2021-8.jpg",
      "/carros/chevrolet-onix-2021-9.jpg"
    ]
  },
  {
    "id": 11,
    "destaque": false,
    "marca": "Chevrolet",
    "modelo": "Onix Plus",
    "versao": "Plus LT 1.0 12V 4P Mec. G",
    "ano": 2024,
    "anoModelo": 2024,
    "km": 102000,
    "uso": "seminovo",
    "cambio": "manual",
    "combustivel": "Flex",
    "cor": "Branco",
    "preco": 74900,
    "img": "/carros/chevrolet-onix-sedan-2024-1.jpg",
    "heroImg": "",
    "opcionais": [
      "Ar-condicionado",
      "MyLink",
      "Câmera de ré",
      "Direção elétrica"
    ],
    "desc": "Onix Sedan Plus LT completo. Espaçoso.",
    "fotos": [
      "/carros/chevrolet-onix-sedan-2024-1.jpg",
      "/carros/chevrolet-onix-sedan-2024-2.jpg",
      "/carros/chevrolet-onix-sedan-2024-3.jpg",
      "/carros/chevrolet-onix-sedan-2024-4.jpg",
      "/carros/chevrolet-onix-sedan-2024-5.jpg",
      "/carros/chevrolet-onix-sedan-2024-6.jpg",
      "/carros/chevrolet-onix-sedan-2024-7.jpg",
      "/carros/chevrolet-onix-sedan-2024-8.jpg",
      "/carros/chevrolet-onix-sedan-2024-9.jpg",
      "/carros/chevrolet-onix-sedan-2024-10.jpg"
    ]
  },
  {
    "id": 12,
    "destaque": false,
    "marca": "Chevrolet",
    "modelo": "Classic",
    "versao": "LS 1.0 4P Mec. G Completo",
    "ano": 2014,
    "anoModelo": 2015,
    "km": 135000,
    "uso": "usado",
    "cambio": "manual",
    "combustivel": "Flex",
    "cor": "Branco",
    "preco": 43900,
    "img": "/carros/classic-ls-2015.jpg",
    "heroImg": "/carros/classic-hero.png",
    "opcionais": [
      "Ar-condicionado",
      "Direção hidráulica",
      "Vidros elétricos",
      "Trava elétrica"
    ],
    "desc": "Classic LS 1.0 completo. Econômico e confiável."
  },
  {
    "id": 14,
    "destaque": false,
    "marca": "Renault",
    "modelo": "Kwid Zen",
    "versao": "1.0 Flex 12V 5 Pts Mecânico Completo",
    "ano": 2023,
    "anoModelo": 2024,
    "km": 64000,
    "uso": "seminovo",
    "cambio": "manual",
    "combustivel": "Flex",
    "cor": "Branco",
    "preco": 59900,
    "img": "/carros/renault-kwid-zen-2023-4.jpg",
    "heroImg": "",
    "opcionais": [
      "Ar-condicionado",
      "Direção elétrica",
      "Vidros elétricos",
      "Central multimídia"
    ],
    "desc": "Kwid Zen 1.0 completo. Compacto e econômico.",
    "fotos": [
      "/carros/renault-kwid-zen-2023-4.jpg",
      "/carros/renault-kwid-zen-2023-10.jpg",
      "/carros/renault-kwid-zen-2023-1.jpg",
      "/carros/renault-kwid-zen-2023-2.jpg",
      "/carros/renault-kwid-zen-2023-3.jpg",
      "/carros/renault-kwid-zen-2023-5.jpg",
      "/carros/renault-kwid-zen-2023-6.jpg",
      "/carros/renault-kwid-zen-2023-7.jpg",
      "/carros/renault-kwid-zen-2023-8.jpg",
      "/carros/renault-kwid-zen-2023-9.jpg"
    ]
  },
  {
    "id": 15,
    "destaque": false,
    "marca": "Hyundai",
    "modelo": "HB20",
    "versao": "Sense 1.0 Flex 12V MEC. G Completo",
    "ano": 2022,
    "anoModelo": 2023,
    "km": 88500,
    "uso": "seminovo",
    "cambio": "manual",
    "combustivel": "Flex",
    "cor": "Preto",
    "preco": 62900,
    "img": "/carros/hb20-sense-2023.jpg",
    "heroImg": "/carros/hb20-hero.png",
    "opcionais": [
      "Ar-condicionado",
      "Direção elétrica",
      "Vidros elétricos",
      "Central multimídia",
      "Alarme"
    ],
    "desc": "HB20 Sense 1.0 Flex completo. Design moderno."
  },
  {
    "id": 16,
    "destaque": false,
    "marca": "Hyundai",
    "modelo": "HB20",
    "versao": "Confort 1.0 Flex 12V MEC. G Completo",
    "ano": 2023,
    "anoModelo": 2024,
    "km": 119000,
    "uso": "seminovo",
    "cambio": "manual",
    "combustivel": "Flex",
    "cor": "Preto",
    "preco": 67900,
    "img": "/carros/hb20-confort.jpg",
    "heroImg": "",
    "opcionais": [
      "Ar-condicionado",
      "Direção elétrica",
      "Vidros elétricos",
      "Central multimídia",
      "Câmera de ré"
    ],
    "desc": "HB20 Confort 1.0 completo. Modelo atualizado."
  },
  {
    "id": 17,
    "destaque": false,
    "marca": "Hyundai",
    "modelo": "HB20S",
    "versao": "Confort Sedan 1.0 Flex 12V MEC. G Completo",
    "ano": 2025,
    "anoModelo": 2025,
    "km": 94600,
    "uso": "seminovo",
    "cambio": "manual",
    "combustivel": "Flex",
    "cor": "Azul",
    "preco": 78900,
    "img": "/carros/hyundai-hb20s-2025-1.jpg",
    "heroImg": "",
    "opcionais": [
      "Ar-condicionado",
      "Direção elétrica",
      "Vidros elétricos",
      "Central multimídia",
      "Câmera de ré"
    ],
    "desc": "HB20S Confort Sedan completo. Modelo 2025.",
    "fotos": [
      "/carros/hyundai-hb20s-2025-1.jpg",
      "/carros/hyundai-hb20s-2025-2.jpg",
      "/carros/hyundai-hb20s-2025-3.jpg",
      "/carros/hyundai-hb20s-2025-4.jpg",
      "/carros/hyundai-hb20s-2025-5.jpg",
      "/carros/hyundai-hb20s-2025-6.jpg",
      "/carros/hyundai-hb20s-2025-7.jpg",
      "/carros/hyundai-hb20s-2025-8.jpg",
      "/carros/hyundai-hb20s-2025-9.jpg",
      "/carros/hyundai-hb20s-2025-10.jpg"
    ]
  },
  {
    "id": 18,
    "destaque": false,
    "marca": "Hyundai",
    "modelo": "Tucson",
    "versao": "2.0 16V Mecânica",
    "ano": 2009,
    "anoModelo": 2010,
    "km": 269710,
    "uso": "usado",
    "cambio": "manual",
    "combustivel": "Gasolina",
    "cor": "Prata",
    "preco": 46900,
    "img": "/carros/hyundai-tucson-2009-2.jpg",
    "heroImg": "",
    "opcionais": [
      "Ar-condicionado",
      "Direção hidráulica",
      "Vidros elétricos"
    ],
    "desc": "Tucson 2.0 mecânica. SUV espaçosa.",
    "fotos": [
      "/carros/hyundai-tucson-2009-2.jpg",
      "/carros/hyundai-tucson-2009-1.jpg",
      "/carros/hyundai-tucson-2009-3.jpg",
      "/carros/hyundai-tucson-2009-4.jpg",
      "/carros/hyundai-tucson-2009-5.jpg",
      "/carros/hyundai-tucson-2009-6.jpg",
      "/carros/hyundai-tucson-2009-7.jpg",
      "/carros/hyundai-tucson-2009-8.jpg",
      "/carros/hyundai-tucson-2009-9.jpg",
      "/carros/hyundai-tucson-2009-10.jpg"
    ]
  },
  {
    "id": 19,
    "destaque": false,
    "marca": "Citroën",
    "modelo": "C3",
    "versao": "Live Pack 1.0 MT Flex 5p Completo",
    "ano": 2024,
    "anoModelo": 2025,
    "km": 62000,
    "uso": "seminovo",
    "cambio": "manual",
    "combustivel": "Flex",
    "cor": "Cinza",
    "preco": 72500,
    "img": "/carros/citroen-c3-2024-9.jpg",
    "heroImg": "",
    "opcionais": [
      "Ar-condicionado",
      "Direção elétrica",
      "Vidros elétricos",
      "Central multimídia"
    ],
    "desc": "C3 Live Pack 1.0 completo. Design moderno.",
    "fotos": [
      "/carros/citroen-c3-2024-9.jpg",
      "/carros/citroen-c3-2024-1.jpg",
      "/carros/citroen-c3-2024-2.jpg",
      "/carros/citroen-c3-2024-3.jpg",
      "/carros/citroen-c3-2024-4.jpg",
      "/carros/citroen-c3-2024-5.jpg",
      "/carros/citroen-c3-2024-6.jpg",
      "/carros/citroen-c3-2024-7.jpg",
      "/carros/citroen-c3-2024-8.jpg",
      "/carros/citroen-c3-2024-10.jpg",
      "/carros/citroen-c3-2024-11.jpg",
      "/carros/citroen-c3-2024-12.jpg",
      "/carros/citroen-c3-2024-13.jpg",
      "/carros/citroen-c3-2024-14.jpg",
      "/carros/citroen-c3-2024-15.jpg",
      "/carros/citroen-c3-2024-16.jpg"
    ]
  },
  {
    "id": 20,
    "destaque": false,
    "marca": "Citroën",
    "modelo": "C3 Aircross",
    "versao": "GLX 1.6 16V Completo",
    "ano": 2011,
    "anoModelo": 2011,
    "km": 156000,
    "uso": "usado",
    "cambio": "manual",
    "combustivel": "Flex",
    "cor": "Prata",
    "preco": 39900,
    "img": "/carros/citroen-c3-aircross-2011-1.jpg",
    "heroImg": "",
    "opcionais": [
      "Ar-condicionado",
      "Direção elétrica",
      "Vidros elétricos"
    ],
    "desc": "C3 Aircross GLX 1.6 completo. Versátil.",
    "fotos": [
      "/carros/citroen-c3-aircross-2011-1.jpg",
      "/carros/citroen-c3-aircross-2011-2.jpg",
      "/carros/citroen-c3-aircross-2011-3.jpg",
      "/carros/citroen-c3-aircross-2011-4.jpg",
      "/carros/citroen-c3-aircross-2011-5.jpg",
      "/carros/citroen-c3-aircross-2011-6.jpg",
      "/carros/citroen-c3-aircross-2011-7.jpg",
      "/carros/citroen-c3-aircross-2011-8.jpg",
      "/carros/citroen-c3-aircross-2011-9.jpg",
      "/carros/citroen-c3-aircross-2011-10.jpg",
      "/carros/citroen-c3-aircross-2011-11.jpg"
    ]
  },
  {
    "id": 21,
    "destaque": true,
    "marca": "BMW",
    "modelo": "118i",
    "versao": "2.0 16V Completa",
    "ano": 2009,
    "anoModelo": 2010,
    "km": 80500,
    "uso": "usado",
    "cambio": "automático",
    "combustivel": "Gasolina",
    "cor": "Cinza",
    "preco": 59900,
    "img": "/carros/bmw-118i-2010.jpg",
    "heroImg": "/carros/bmw-hero.png",
    "opcionais": [
      "Ar-condicionado",
      "Direção elétrica",
      "Teto solar",
      "Bancos em couro",
      "Rodas 18\""
    ],
    "desc": "BMW 118i 2.0 16V automática completa. Esportiva."
  },
  {
    "id": 22,
    "destaque": true,
    "marca": "Toyota",
    "modelo": "Corolla",
    "versao": "XEi Flex 2.0 Completo",
    "ano": 2014,
    "anoModelo": 2015,
    "km": 85500,
    "uso": "usado",
    "cambio": "automático",
    "combustivel": "Flex",
    "cor": "Cinza",
    "preco": 89900,
    "img": "/carros/corolla-xei-2015.jpg",
    "heroImg": "/carros/corolla-hero.png",
    "opcionais": [
      "Ar-condicionado",
      "Direção elétrica",
      "Bancos em couro",
      "Câmera de ré",
      "Central multimídia"
    ],
    "desc": "Corolla XEi 2.0 Flex automático completo. Revisado."
  },
  {
    "id": 23,
    "destaque": false,
    "marca": "Chevrolet",
    "modelo": "Onix Plus",
    "versao": "Lt 1.0 Completo",
    "ano": 2024,
    "anoModelo": 2024,
    "km": 67348,
    "uso": "seminovo",
    "cambio": "manual",
    "combustivel": "Flex",
    "cor": "Preto",
    "preco": 72500,
    "img": "/carros/onix-plus.jpg",
    "heroImg": "",
    "opcionais": [
      "Ar-condicionado",
      "MyLink",
      "Câmera de ré",
      "Wi-Fi"
    ],
    "desc": "Onix Plus LT 1.0 completo. Sedan moderno."
  },
  {
    "id": 24,
    "destaque": false,
    "marca": "Citroën",
    "modelo": "C3",
    "versao": "Live Pack 1.0 MT Flex 5p Completo",
    "ano": 2024,
    "anoModelo": 2025,
    "km": 124327,
    "uso": "seminovo",
    "cambio": "manual",
    "combustivel": "Flex",
    "cor": "Preto",
    "preco": 72900,
    "img": "/carros/c3-preto.jpg",
    "heroImg": "",
    "opcionais": [
      "Ar-condicionado",
      "Direção elétrica",
      "Central multimídia"
    ],
    "desc": "C3 Live Pack completo. Econômico."
  },
  {
    "id": 25,
    "destaque": false,
    "marca": "Fiat",
    "modelo": "Cronos",
    "versao": "1.0 Completo",
    "ano": 2022,
    "anoModelo": 2023,
    "km": 85835,
    "uso": "seminovo",
    "cambio": "manual",
    "combustivel": "Flex",
    "cor": "Branco",
    "preco": 61900,
    "img": "/carros/cronos-branco.jpg",
    "heroImg": "",
    "opcionais": [
      "Ar-condicionado",
      "Direção elétrica",
      "Central multimídia"
    ],
    "desc": "Cronos 1.0 completo. Revisado."
  },
  {
    "id": 26,
    "destaque": false,
    "marca": "Fiat",
    "modelo": "Mobi",
    "versao": "Like 1.0 Completo",
    "ano": 2019,
    "anoModelo": 2020,
    "km": 202921,
    "uso": "usado",
    "cambio": "manual",
    "combustivel": "Flex",
    "cor": "Prata",
    "preco": 49900,
    "img": "/carros/fiat-mobi-2019-1.jpg",
    "heroImg": "",
    "opcionais": [
      "Ar-condicionado",
      "Direção elétrica",
      "Vidros elétricos"
    ],
    "desc": "Mobi Like 1.0 completo. Compacto e econômico.",
    "fotos": [
      "/carros/fiat-mobi-2019-1.jpg",
      "/carros/fiat-mobi-2019-2.jpg",
      "/carros/fiat-mobi-2019-3.jpg",
      "/carros/fiat-mobi-2019-4.jpg",
      "/carros/fiat-mobi-2019-5.jpg",
      "/carros/fiat-mobi-2019-6.jpg",
      "/carros/fiat-mobi-2019-7.jpg",
      "/carros/fiat-mobi-2019-8.jpg"
    ]
  },
  {
    "id": 27,
    "destaque": false,
    "marca": "Renault",
    "modelo": "Logan",
    "versao": "Zen 1.0 Completo",
    "ano": 2020,
    "anoModelo": 2021,
    "km": 275262,
    "uso": "usado",
    "cambio": "manual",
    "combustivel": "Flex",
    "cor": "Prata",
    "preco": 49900,
    "img": "/carros/logan.jpg",
    "heroImg": "",
    "opcionais": [
      "Ar-condicionado",
      "Direção elétrica",
      "Central multimídia"
    ],
    "desc": "Logan Zen 1.0 completo. Sedan espaçoso."
  },
  {
    "id": 28,
    "destaque": false,
    "marca": "Renault",
    "modelo": "Kwid",
    "versao": "Zen 1.0 Completo",
    "ano": 2023,
    "anoModelo": 2024,
    "km": 45276,
    "uso": "seminovo",
    "cambio": "manual",
    "combustivel": "Flex",
    "cor": "Prata",
    "preco": 57900,
    "img": "/carros/kwid-prata.jpg",
    "heroImg": "",
    "opcionais": [
      "Ar-condicionado",
      "Direção elétrica",
      "Central multimídia"
    ],
    "desc": "Kwid Zen 1.0 completo. Baixa km."
  },
  {
    "id": 29,
    "destaque": false,
    "marca": "Suzuki",
    "modelo": "GSX-R 750",
    "versao": "SRAD",
    "ano": 2010,
    "anoModelo": 2011,
    "km": 0,
    "uso": "usado",
    "cambio": "manual",
    "combustivel": "Gasolina",
    "cor": "Branca",
    "preco": 39900,
    "img": "/carros/suzuki-gsx-r-750-2010-1.jpg",
    "heroImg": "",
    "opcionais": [],
    "desc": "GSX-R 750 SRAD. Moto esportiva em excelente estado.",
    "fotos": [
      "/carros/suzuki-gsx-r-750-2010-1.jpg",
      "/carros/suzuki-gsx-r-750-2010-2.jpg",
      "/carros/suzuki-gsx-r-750-2010-3.jpg",
      "/carros/suzuki-gsx-r-750-2010-4.jpg",
      "/carros/suzuki-gsx-r-750-2010-5.jpg",
      "/carros/suzuki-gsx-r-750-2010-6.jpg",
      "/carros/suzuki-gsx-r-750-2010-7.jpg",
      "/carros/suzuki-gsx-r-750-2010-8.jpg"
    ]
  }
];
